name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  pipeline:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-freebsd
            bin: uploadstr
            name: uploadstr-x86_64-unknown-freebsd
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: uploadstr.exe
            name: uploadstr-x86_64-pc-windows-msvc.exe
          - os: macOS-latest
            target: x86_64-apple-darwin
            bin: uploadstr
            name: uploadstr-x86_64-apple-darwin
            
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: full
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Build
        run: cargo build -r && mv target/release/${{matrix.bin}} target/release/${{matrix.name}}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.branch == "master"
        with:
          files: |
            target/release/${{matrix.name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
